package cn.itcast.bos.domain.bc;

// Generated 2017-7-18 21:41:19 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Subarea generated by hbm2java
 */
@Entity
@Table(name = "bc_subarea", catalog = "maven_ssh")
public class Subarea implements java.io.Serializable {

	private String id;
	private DecidedZone decidedZone;
	private Region region;
	private String addresskey;
	private String startnum;
	private String endnum;
	private Character oodnum;
	private String position;

	@Transient
	public String getSid() {
		return this.id;
	}

	public Subarea() {
	}

	public Subarea(DecidedZone decidedZone, Region region, String addresskey,
			String startnum, String endnum, Character oodnum, String position) {
		this.decidedZone = decidedZone;
		this.region = region;
		this.addresskey = addresskey;
		this.startnum = startnum;
		this.endnum = endnum;
		this.oodnum = oodnum;
		this.position = position;
	}

	@GenericGenerator(name = "generator", strategy = "uuid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DECIDEDZONE_ID")
	@JSONField(serialize = false)
	public DecidedZone getDecidedZone() {
		return this.decidedZone;
	}

	public void setDecidedZone(DecidedZone decidedZone) {
		this.decidedZone = decidedZone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGION_ID")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "ADDRESSKEY", length = 100)
	public String getAddresskey() {
		return this.addresskey;
	}

	public void setAddresskey(String addresskey) {
		this.addresskey = addresskey;
	}

	@Column(name = "STARTNUM", length = 30)
	public String getStartnum() {
		return this.startnum;
	}

	public void setStartnum(String startnum) {
		this.startnum = startnum;
	}

	@Column(name = "ENDNUM", length = 30)
	public String getEndnum() {
		return this.endnum;
	}

	public void setEndnum(String endnum) {
		this.endnum = endnum;
	}

	@Column(name = "OODNUM", length = 1)
	public Character getOodnum() {
		return this.oodnum;
	}

	public void setOodnum(Character oodnum) {
		this.oodnum = oodnum;
	}

	@Column(name = "POSITION")
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

}
